# Site settings
title: Kubeify
email: dinesh@codecrux.com
description: > # this means to ignore newlines until "baseurl:"
    Make your cloud native transformation with Kubernetes and support from kubeify's team of experts

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kubeify.io" # the base hostname & protocol for your site
twitter_username: kubeify
github_username:  kubeify

# Build settings
markdown: kramdown
