# Site settings
title: DataCol
email: dinesh@codecrux.com
description: > # this means to ignore newlines until "baseurl:"
  Datacol is the easiest way to connect salesforce to your back-office data system.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://datacol.io" # the base hostname & protocol for your site
twitter_username: datacol
github_username:  datacol

# Build settings
markdown: kramdown
